environment:
    prompt_path: './examples/customer_service/input/call_agent_prompt.md'
    tools_file: ''
    database_folder: ''
    database_validators: ''

dataset:
    num_samples: 10
    cost_limit: 3 #In dollars

dialog_manager:
    cost_limit: 3 